# Generated by Django 4.2.7 on 2026-01-10 21:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this transcription request', primary_key=True, serialize=False)),
                ('audio_filename', models.CharField(help_text='Name of the audio file', max_length=255)),
                ('audio_file_path', models.CharField(help_text='Full path to the audio file', max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the transcription', max_length=20)),
                ('transcribed_text', models.TextField(blank=True, help_text='The transcribed text result', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if transcription failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the transcription request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the transcription was last updated')),
            ],
            options={
                'verbose_name': 'Transcription',
                'verbose_name_plural': 'Transcriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
