# Generated by Django 4.2.7 on 2026-01-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='image_path',
            field=models.CharField(blank=True, help_text='Full path to the generated image file', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='image_raw',
            field=models.BinaryField(blank=True, help_text='Raw binary data for the processed image', null=True),
        ),
    ]
