# Generated by Django 4.2.7 on 2026-01-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transcription_image_path_transcription_image_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=255, unique=True)),
                ('image_available', models.BooleanField(default=False, help_text='Whether an image is available for this device')),
                ('image_path', models.CharField(blank=True, help_text='Full path to the generated image file', max_length=512, null=True)),
                ('image_raw', models.BinaryField(blank=True, help_text='Raw binary data for the processed image', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the device image record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the device image was last updated')),
            ],
            options={
                'verbose_name': 'Device Image',
                'verbose_name_plural': 'Device Images',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='transcription',
            name='device_id',
            field=models.CharField(blank=True, help_text='Device ID from query parameter', max_length=255, null=True),
        ),
    ]
