# Generated by Django 4.2.7 on 2026-02-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_deviceimage_transcription_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceimage',
            name='transcript',
            field=models.TextField(blank=True, help_text='The transcribed text', null=True),
        ),
        migrations.AddField(
            model_name='deviceimage',
            name='transcript_available',
            field=models.BooleanField(default=False, help_text='Whether a transcript is available for this device'),
        ),
    ]
